### ISSUE TITLE
While `auto.create.topics.enable` is enabled getting `UnknownTopicOrPartition` errors

### ISSUE THREAD

**Issue by Fristi** [manub/scalatest-embedded-kafka#30]
While `auto.create.topics.enable` is enabled I get `UnknownTopicOrPartition` errors

When I add this piece of code to make a randomTopic it seems to work:

```scala
  def randomTopic = {
    val name = s"test${System.nanoTime().toString}"
    EmbeddedKafka.createCustomTopic(name)
    Thread.sleep(50)
    name
  }
```

**Comment by slavaschmidt** [comment]
We might have a related issue. 

Our Kafka client version 0.10.0.0

We were able to address the issue in our environment like following:

It turns out that the Kafka client is lazy initialised, for this reason the very first call to the producer takes quite a long time. 
Because of this a CircuitBreaker was stepping in and delivered a timeout. 

As a workaround we are now eager initialising the producer by querying the metadata from Kafka before sending the first message like this:

```
def eagerInit(topic: String = "well_known"): util.List[PartitionInfo] = producer.partitionsFor(topic)
```
After that the send/recieve methods seem to work as expected.

**Comment by manub** [comment]
@slavaschmidt by _client_ do you mean the `producer`?

I can see the issue here and I know we've discussed it on Twitter but I'm unable to replicate it on my machine. 

I've written another test and it seems to pass on my machine - could you please look at it, see if it makes sense and try it on yours? Gist is available at https://gist.github.com/manub/17e106ad69c494c4cedb6e32df40a65e

**Comment by Fristi** [comment]
@slavaschmidt That might be worth a try. I'll dig in to that :-)

@manub && @slavaschmidt: I am writing a native pure scala driver for kafka, so for that reason I would like to use my own driver, but I could use the official kafka client in my test to force such behavior

**Comment by manub** [comment]
@Fristi let me know if using the trick proposed by @slavaschmidt you fix your problem.

**Comment by manub** [comment]
Do you still have the problem @Fristi? Please let me know so I can update the issue.

**Comment by Fristi** [comment]
Issue is solved, I had to switch to Docker for testing.
